"""`sanguo-art`: build the game's portraits from pics/art.json.

pics/art.json is the single place art is configured:
  "portraits": {
    "<key>": {"src": "source/generals/sunce.jpg",   # image under pics/ (any size, jpg/png/webp)
              "face": [0.49, 0.22],          # face centre, as fractions of width/height
              "head": 0.10,                  # head height / image height (sets close-up tightness)
              "placeholder": true,           # optional: stand-in art, not final
              "source": "https://…", "license": "Public domain", "artist": "…",   # optional provenance
              "prep": {"from": "source/soldiers/x.jpg", "cut_top": 0.15, "figure": 0.7}}  # optional, see below
  }
Raw images live in pics/source/ (never modified); anything a tool derives goes to pics/processed/.
An entry with "prep" is regenerated first: tools/prep_art.py cuts a title band off "from" and pads it
into "src", so the figure can be framed smaller.
<key> is a card id or a person id (all versions of that person share it), or an enemy's "portrait".

Running it shrinks every source into godot/data/portraits/, rewrites portraits.json, and regenerates
pics/ART-NEEDS.md (what still needs art) and pics/SOURCES.md (where each image came from).
Entries whose source image is missing keep their already-built portrait, so a fresh clone without the
original pictures still works.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from PIL import Image

from .cards import CardDB, load_db

ROOT = Path(__file__).resolve().parents[2]
PICS = ROOT / "pics"
OUT = ROOT / "godot" / "data" / "portraits"  # the Godot project is the game now
MAX_H = 640
MAP_OUT = ROOT / "godot" / "data" / "art" / "map"
MAP_H = 800


def _prep():
    import importlib.util

    spec = importlib.util.spec_from_file_location("prep_art", ROOT / "tools" / "prep_art.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.prep


def build(pics: Path = PICS, out: Path = OUT) -> list[str]:
    cfg = json.loads((pics / "art.json").read_text("utf-8"))["portraits"]
    index = {}
    built = []
    for key, e in cfg.items():
        if key.startswith("_"):
            continue
        dst = out / f"{key}.jpg"
        src = pics / e["src"]
        prep = e.get("prep")
        if prep and (pics / prep["from"]).exists():
            _prep()(pics / prep["from"], src, float(prep.get("cut_top", 0.15)), float(prep.get("figure", 0.7)))
        if src.exists():
            im = Image.open(src)
            if im.mode in ("RGBA", "LA", "P"):  # flatten transparent art onto the paper colour
                im = im.convert("RGBA")
                bg = Image.new("RGBA", im.size, (246, 243, 234, 255))
                bg.alpha_composite(im)
                im = bg
            im = im.convert("RGB")
            if im.height > MAX_H:
                im = im.resize((round(im.width * MAX_H / im.height), MAX_H), Image.LANCZOS)
            im.save(dst, quality=88)
            built.append(key)
        elif not dst.exists():
            print(f"  ! {key}: {src.name} not found and no built copy — skipped")
            continue
        entry = {"file": dst.name, "face": e["face"], "head": e["head"]}
        if e.get("placeholder"):
            entry["placeholder"] = True
        index[key] = entry
    lines = ['  "_comment": "GENERATED by `sanguo-art` from pics/art.json — edit that file instead"']
    lines += [f'  "{k}": ' + json.dumps(v, ensure_ascii=False) for k, v in index.items()]
    (out / "portraits.json").write_text("{\n" + ",\n".join(lines) + "\n}\n", "utf-8")
    return built


def build_maps(pics: Path = PICS, out: Path = MAP_OUT) -> list[str]:
    """Chapter map backgrounds: "maps" in art.json, keyed by quest id → godot/data/art/map/<id>.jpg."""
    cfg = json.loads((pics / "art.json").read_text("utf-8")).get("maps", {})
    out.mkdir(parents=True, exist_ok=True)
    built = []
    for key, e in cfg.items():
        src = pics / e["src"]
        if not src.exists():
            continue
        im = Image.open(src).convert("RGB")
        if im.height > MAP_H:
            im = im.resize((round(im.width * MAP_H / im.height), MAP_H), Image.LANCZOS)
        im.save(out / f"{key}.jpg", quality=88)
        built.append(key)
    return built


# ---- reports -------------------------------------------------------------------

def _status(cfg: dict, key: str) -> str:
    if key not in cfg:
        return "⬜ 缺"
    return "🟡 占位" if cfg[key].get("placeholder") else "✅ 正式"


def write_needs(pics: Path = PICS) -> None:
    """ART-NEEDS.md from the Godot game data: what each chapter shows that still has no (final) art."""
    NL = chr(10)
    cfg = json.loads((pics / "art.json").read_text("utf-8"))["portraits"]
    data = ROOT / "godot" / "data"
    cards = json.loads((data / "cards.json").read_text("utf-8"))
    story = json.loads((data / "story.json").read_text("utf-8"))
    names = {cid: c["name"] for cid, c in cards["cards"].items()}

    def key_of(cid: str) -> str:
        return cards["cards"][cid].get("person", cid.split("_")[0] if cid.endswith("_card") else cid)

    def status(key: str) -> str:
        if key not in cfg:
            return "⬜ 缺"
        return "🟡 占位" if cfg[key].get("placeholder") else "✅ 正式"

    seen: set[str] = set()

    def rows(items: list[tuple[str, str]]) -> list[str]:
        out = []
        for key, what in items:
            if key in seen:
                continue
            seen.add(key)
            out.append(f"| {status(key)} | `{key}` | {what} |")
        return out or ["| ✅ | — | 都有了 |"]

    def chapter(q: dict) -> list[str]:
        people: list[tuple[str, str]] = []
        enemies: list[tuple[str, str]] = []
        loot: list[tuple[str, str]] = []
        for s in q["squares"].values():
            for pk in s.get("portraits", []):
                people.append((pk, "剧情立绘"))
            for c in s.get("cards", []):
                loot.append((key_of(c), names[c]))
            for o in s.get("choose", []):
                if o.get("card"):
                    loot.append((key_of(o["card"]), names[o["card"]]))
            fights = [s["battle"]] if s.get("battle") else []
            for ev in [story["events"].get(s.get("event", ""))] + [story["events"][e] for e in q.get("event_pool", [])]:
                if not ev:
                    continue
                for pk in ev.get("portraits", []):
                    people.append((pk, f"事件「{ev['title']}」"))
                for o in ev["options"]:
                    fights += [e["battle"] for e in o.get("effects", []) if "battle" in e]
            for f in fights:
                e = cards["enemies"][cards["scenarios"][f]["enemy"]]
                enemies.append((e.get("portrait") or cards["scenarios"][f]["enemy"], e["name"]))
                if e.get("card"):
                    loot.append((key_of(e["card"]), f"{names[e['card']]}（{e['name']}的卡）"))
        for c in q.get("soldier_pool", []) + q.get("recruit_pool", []):
            loot.append((key_of(c), names[c]))
        return (["", f"## {q['title']}", "", "| 状态 | key | 用在 |", "|---|---|---|"]
                + rows([("lord", "主公 / 穿越者")] + people)
                + ["", "敌人（战斗界面上方；和它的卡共用一张图）", "", "| 状态 | key | 敌人 |", "|---|---|---|"] + rows(enemies)
                + ["", "能拿到的卡", "", "| 状态 | key | 卡 |", "|---|---|---|"] + rows(loot))

    out = [
        "# 美术需求",
        "",
        "> 本文件由 `sanguo-art` 根据游戏数据（godot/data）和 `pics/art.json` 自动生成，别手改。",
        "> 卡框、地图、宝物图标等非立绘需求见 `CARD-DESIGN.md`。",
        "",
        "## 怎么换图",
        "",
        "1. 把原图放进 `pics/source/` 对应的子文件夹（generals 武将 / soldiers 兵卡 / map 地图），文件名用 key（如 `langlijiao.jpg`）。",
        "2. 在 `pics/art.json` 的 `portraits` 里加一行：`\"<key>\": {\"src\": \"source/generals/<key>.jpg\", \"face\": [x, y], \"head\": h}`",
        "   - `face`：脸中心在图里的位置（0–1，左上角是 0,0）；`head`：头高占整图高的比例（越大人物越小）",
        "   - 换掉占位图时，把 `\"placeholder\": true` 删掉",
        "3. 运行 `sanguo-art`。",
        "",
        "规格：竖版 5:7（≥ 1000×1400），人物居中、脸在上 1/3，半身到全身，背景简单。",
        "",
        "状态：✅ 正式美术　🟡 占位图（清代绣像等公有领域图）　⬜ 缺",
    ]
    for q in story["quests"]:
        out += chapter(q)
    rest = [(key_of(cid), c["name"] + f"（{c['rarity']}）") for cid, c in cards["cards"].items()
            if c["rarity"] != "N" and key_of(cid) not in seen]
    rest.sort(key=lambda r: {"SSR": 0, "SR": 1, "R": 2}.get(r[1][-3:-1].strip("（"), 3))
    out += ["", "## 其余武将（招募池，按需再画）", "", "| 状态 | key | 卡 |", "|---|---|---|"] + rows(rest)
    (pics / "ART-NEEDS.md").write_text(NL.join(out) + NL, "utf-8")


def write_sources(pics: Path = PICS) -> None:
    cfg = json.loads((pics / "art.json").read_text("utf-8"))["portraits"]
    out = ["# 图片来源", "", "> 由 `sanguo-art` 根据 `pics/art.json` 生成。", "",
           "| key | 文件 | 来源 | 协议 | 作者 |", "|---|---|---|---|---|"]
    maps = json.loads((pics / "art.json").read_text("utf-8")).get("maps", {})
    for key, e in [*cfg.items(), *((f"map:{k}", v) for k, v in maps.items())]:
        if key.startswith("_"):
            continue
        src = f"[链接]({e['source']})" if e.get("source") else "用户提供"
        out.append(f"| `{key}` | {e['src']} | {src} | {e.get('license', '—')} | {e.get('artist', '—')} |")
    (pics / "SOURCES.md").write_text("\n".join(out) + "\n", "utf-8")


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(prog="sanguo-art", description="从 pics/art.json 生成游戏头像")
    ap.parse_args(argv)
    built = build()
    maps = build_maps()
    if maps:
        print(f"built {len(maps)} map backgrounds → {MAP_OUT}")
    write_needs()
    write_sources()
    print(f"built {len(built)} portraits → {OUT}")
    print(f"updated {PICS / 'ART-NEEDS.md'} and {PICS / 'SOURCES.md'}")


if __name__ == "__main__":
    main()
