"""`sanguo-art`: build the game's portraits from pics/art.json.

pics/art.json is the single place art is configured:
  "portraits": {
    "<key>": {"src": "source/generals/sunce.jpg",   # image under pics/ (any size, jpg/png/webp)
              "face": [0.49, 0.22],          # face centre, as fractions of width/height
              "head": 0.10,                  # head height / image height (sets close-up tightness)
              "placeholder": true,           # optional: stand-in art, not final
              "source": "https://…", "license": "Public domain", "artist": "…",   # optional provenance
              "prep": {"from": "source/soldiers/x.jpg", "cut_top": 0.15, "figure": 0.7}}  # optional, see below
  }
Raw images live in pics/source/ (never modified); anything a tool derives goes to pics/processed/.
An entry with "prep" is regenerated first: tools/prep_art.py cuts a title band off "from" and pads it
into "src", so the figure can be framed smaller.
<key> is a card id or a person id (all versions of that person share it), or an enemy's "portrait".

Running it shrinks every source into godot/data/portraits/, rewrites portraits.json, and regenerates
pics/ART-NEEDS.md (what still needs art) and pics/SOURCES.md (where each image came from).
Entries whose source image is missing keep their already-built portrait, so a fresh clone without the
original pictures still works.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from PIL import Image

from .cards import CardDB, load_db

ROOT = Path(__file__).resolve().parents[2]
PICS = ROOT / "pics"
OUT = ROOT / "godot" / "data" / "portraits"  # the Godot project is the game now
MAX_H = 640
MAP_OUT = ROOT / "godot" / "data" / "art" / "map"
MAP_H = 800


def _prep():
    import importlib.util

    spec = importlib.util.spec_from_file_location("prep_art", ROOT / "tools" / "prep_art.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.prep


def build(pics: Path = PICS, out: Path = OUT) -> list[str]:
    cfg = json.loads((pics / "art.json").read_text("utf-8"))["portraits"]
    index = {}
    built = []
    for key, e in cfg.items():
        if key.startswith("_"):
            continue
        dst = out / f"{key}.jpg"
        src = pics / e["src"]
        prep = e.get("prep")
        if prep and (pics / prep["from"]).exists():
            _prep()(pics / prep["from"], src, float(prep.get("cut_top", 0.15)), float(prep.get("figure", 0.7)))
        if src.exists():
            im = Image.open(src)
            if im.mode in ("RGBA", "LA", "P"):  # flatten transparent art onto the paper colour
                im = im.convert("RGBA")
                bg = Image.new("RGBA", im.size, (246, 243, 234, 255))
                bg.alpha_composite(im)
                im = bg
            im = im.convert("RGB")
            if im.height > MAX_H:
                im = im.resize((round(im.width * MAX_H / im.height), MAX_H), Image.LANCZOS)
            im.save(dst, quality=88)
            built.append(key)
        elif not dst.exists():
            print(f"  ! {key}: {src.name} not found and no built copy — skipped")
            continue
        entry = {"file": dst.name, "face": e["face"], "head": e["head"]}
        if e.get("placeholder"):
            entry["placeholder"] = True
        index[key] = entry
    lines = ['  "_comment": "GENERATED by `sanguo-art` from pics/art.json — edit that file instead"']
    lines += [f'  "{k}": ' + json.dumps(v, ensure_ascii=False) for k, v in index.items()]
    (out / "portraits.json").write_text("{\n" + ",\n".join(lines) + "\n}\n", "utf-8")
    return built


def build_maps(pics: Path = PICS, out: Path = MAP_OUT) -> list[str]:
    """Chapter map backgrounds: "maps" in art.json, keyed by quest id → godot/data/art/map/<id>.jpg."""
    cfg = json.loads((pics / "art.json").read_text("utf-8")).get("maps", {})
    out.mkdir(parents=True, exist_ok=True)
    built = []
    for key, e in cfg.items():
        src = pics / e["src"]
        if not src.exists():
            continue
        im = Image.open(src).convert("RGB")
        if im.height > MAP_H:
            im = im.resize((round(im.width * MAP_H / im.height), MAP_H), Image.LANCZOS)
        im.save(out / f"{key}.jpg", quality=88)
        built.append(key)
    return built


# ---- reports -------------------------------------------------------------------

def _status(cfg: dict, key: str) -> str:
    if key not in cfg:
        return "⬜ 缺"
    return "🟡 占位" if cfg[key].get("placeholder") else "✅ 正式"


def write_needs(db: CardDB, pics: Path = PICS) -> None:
    cfg = json.loads((pics / "art.json").read_text("utf-8"))["portraits"]
    people: dict[str, list] = {}
    for c in db.cards.values():
        if not c.soldier:
            people.setdefault(c.person, []).append(c)

    def row(key: str, what: str) -> str:
        return f"| {_status(cfg, key)} | `{key}` | {what} |"

    def cards_of(p: str) -> str:
        return " / ".join(f"{c.name}（{c.rarity}·{db.troops[c.troop].name}）" for c in people[p])

    story = sorted({c.person for c in db.cards.values() if not c.in_pool and not c.soldier})
    out = [
        "# 美术需求",
        "",
        "> 本文件由 `sanguo-art` 根据 `pics/art.json` 自动生成，别手改——改 `art.json` 然后重新运行。",
        "",
        "## 怎么换图",
        "",
        "1. 把原图放进 `pics/source/` 对应的子文件夹（generals 武将 / soldiers 兵卡 / frames 卡框），文件名用 key（如 `huanggai.jpg`）。",
        "2. 在 `pics/art.json` 的 `portraits` 里改（或加）一行：",
        '   `"<key>": {"src": "source/generals/<key>.jpg", "face": [x, y], "head": h}`',
        '   - 带标题字的兵卡图：加 `"prep": {"from": "source/soldiers/<key>.jpg", "cut_top": 0.15, "figure": 0.7}`，`src` 写 `processed/<key>_card.jpg`',
        "   - `face`：脸中心在图里的位置（0–1，左上角是 0,0）；`head`：头高占整图高的比例（半身像约 0.2，全身像约 0.07–0.12）",
        '   - 换掉占位图时，把 `"placeholder": true` 删掉',
        "3. 运行 `sanguo-art`：自动缩图、更新游戏里的头像、重新生成本文件和 `SOURCES.md`。",
        "",
        "## 图片规格",
        "",
        "- 竖版立绘，约 3:4，最短边 ≥ 600px。界面里的头像框都是竖的：卡牌和队长卡取胸像，剧情取半身，卡册显示整张。",
        "- 脸要清楚：终端里头像只有约 15×10 个色块，半身像、背景简单的图效果最好。",
        "- 同一人的不同版本（孙策·少年 / 孙策·中年）默认共用一个 key；想分开就用卡牌 id 做 key（如 `sunce_zhong`）。",
        "- 占位图的来源和协议见 `SOURCES.md`。",
        "",
        "状态：✅ 正式美术　🟡 占位图（清代绣像等公有领域图，可用但风格不统一）　⬜ 缺",
        "",
        "## 剧情人物",
        "",
        "| 状态 | key | 卡牌 |",
        "|---|---|---|",
        row("lord", "**主公 / 穿越者**（玩家自己，现代人穿越到东汉末年）"),
        *[row(p, cards_of(p)) for p in story],
        "",
        "## 敌人（战斗界面上方）",
        "",
        "| 状态 | key | 敌人 |",
        "|---|---|---|",
        *[row(e.portrait or e.id, e.name) for e in db.enemies.values()],
        "",
        "## 兵种（兵卡和没有立绘时的占位）",
        "",
        "| 状态 | key | 兵种 |",
        "|---|---|---|",
        *[row(f"troop_{t.id}", t.name) for t in db.troops.values() if t.id != "lord"],
    ]
    for rarity in ("SSR", "SR", "R"):
        ps = [p for p, cs in people.items() if p not in story and max(c.rarity for c in cs) == rarity
              and all(c.rarity in ("R", "SR", "SSR") for c in cs)]
        ps = [p for p in ps if max(("R", "SR", "SSR").index(c.rarity) for c in people[p]) == ("R", "SR", "SSR").index(rarity)]
        out += ["", f"## {rarity}", "", "| 状态 | key | 卡牌 |", "|---|---|---|", *[row(p, cards_of(p)) for p in sorted(ps)]]
    (pics / "ART-NEEDS.md").write_text("\n".join(out) + "\n", "utf-8")


def write_sources(pics: Path = PICS) -> None:
    cfg = json.loads((pics / "art.json").read_text("utf-8"))["portraits"]
    out = ["# 图片来源", "", "> 由 `sanguo-art` 根据 `pics/art.json` 生成。", "",
           "| key | 文件 | 来源 | 协议 | 作者 |", "|---|---|---|---|---|"]
    maps = json.loads((pics / "art.json").read_text("utf-8")).get("maps", {})
    for key, e in [*cfg.items(), *((f"map:{k}", v) for k, v in maps.items())]:
        if key.startswith("_"):
            continue
        src = f"[链接]({e['source']})" if e.get("source") else "用户提供"
        out.append(f"| `{key}` | {e['src']} | {src} | {e.get('license', '—')} | {e.get('artist', '—')} |")
    (pics / "SOURCES.md").write_text("\n".join(out) + "\n", "utf-8")


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(prog="sanguo-art", description="从 pics/art.json 生成游戏头像")
    ap.parse_args(argv)
    built = build()
    maps = build_maps()
    if maps:
        print(f"built {len(maps)} map backgrounds → {MAP_OUT}")
    db = load_db()
    write_needs(db)
    write_sources()
    print(f"built {len(built)} portraits → {OUT}")
    print(f"updated {PICS / 'ART-NEEDS.md'} and {PICS / 'SOURCES.md'}")


if __name__ == "__main__":
    main()
